config/routes.rb
Rails.application.routes.draw do
  resources :arts
  resources :descriptions
  resources :artistes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  belongs_to :artiste
  belongs_to :description
end

app/models/artiste.rb
class Artiste < ApplicationRecord
end

app/models/description.rb
class Description < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artistes_controller.rb
class ArtistesController < ApplicationController
  before_action :set_artiste, only: [:show, :edit, :update, :destroy]

  # GET /artistes
  # GET /artistes.json
  def index
    @artistes = Artiste.all
  end

  # GET /artistes/1
  # GET /artistes/1.json
  def show
  end

  # GET /artistes/new
  def new
    @artiste = Artiste.new
  end

  # GET /artistes/1/edit
  def edit
  end

  # POST /artistes
  # POST /artistes.json
  def create
    @artiste = Artiste.new(artiste_params)

    respond_to do |format|
      if @artiste.save
        format.html { redirect_to @artiste, notice: 'Artiste was successfully created.' }
        format.json { render :show, status: :created, location: @artiste }
      else
        format.html { render :new }
        format.json { render json: @artiste.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artistes/1
  # PATCH/PUT /artistes/1.json
  def update
    respond_to do |format|
      if @artiste.update(artiste_params)
        format.html { redirect_to @artiste, notice: 'Artiste was successfully updated.' }
        format.json { render :show, status: :ok, location: @artiste }
      else
        format.html { render :edit }
        format.json { render json: @artiste.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artistes/1
  # DELETE /artistes/1.json
  def destroy
    @artiste.destroy
    respond_to do |format|
      format.html { redirect_to artistes_url, notice: 'Artiste was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artiste
      @artiste = Artiste.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artiste_params
      params.require(:artiste).permit(:prenom, :nom)
    end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: [:show, :edit, :update, :destroy]

  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1
  # PATCH/PUT /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art.destroy
    respond_to do |format|
      format.html { redirect_to arts_url, notice: 'Art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_params
      params.require(:art).permit(:photo, :date, :dimension, :titre, :artiste_id, :description_id)
    end
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  before_action :set_description, only: [:show, :edit, :update, :destroy]

  # GET /descriptions
  # GET /descriptions.json
  def index
    @descriptions = Description.all
  end

  # GET /descriptions/1
  # GET /descriptions/1.json
  def show
  end

  # GET /descriptions/new
  def new
    @description = Description.new
  end

  # GET /descriptions/1/edit
  def edit
  end

  # POST /descriptions
  # POST /descriptions.json
  def create
    @description = Description.new(description_params)

    respond_to do |format|
      if @description.save
        format.html { redirect_to @description, notice: 'Description was successfully created.' }
        format.json { render :show, status: :created, location: @description }
      else
        format.html { render :new }
        format.json { render json: @description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /descriptions/1
  # PATCH/PUT /descriptions/1.json
  def update
    respond_to do |format|
      if @description.update(description_params)
        format.html { redirect_to @description, notice: 'Description was successfully updated.' }
        format.json { render :show, status: :ok, location: @description }
      else
        format.html { render :edit }
        format.json { render json: @description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /descriptions/1
  # DELETE /descriptions/1.json
  def destroy
    @description.destroy
    respond_to do |format|
      format.html { redirect_to descriptions_url, notice: 'Description was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_description
      @description = Description.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def description_params
      params.require(:description).permit(:technique_utilise, :l_histoire_de_l_oeuvre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artistes_helper.rb
module ArtistesHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/views/artistes/_form.html.erb
<%= form_with(model: artiste, local: true) do |form| %>
  <% if artiste.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artiste.errors.count, "error") %> prohibited this artiste from being saved:</h2>

      <ul>
      <% artiste.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prenom %>
    <%= form.text_field :prenom %>
  </div>

  <div class="field">
    <%= form.label :nom %>
    <%= form.text_field :nom %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artistes/edit.html.erb
<h1>Editing Artiste</h1>

<%= render 'form', artiste: @artiste %>

<%= link_to 'Show', @artiste %> |
<%= link_to 'Back', artistes_path %>

app/views/artistes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artistes</h1>

<table>
  <thead>
    <tr>
      <th>Prenom</th>
      <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artistes.each do |artiste| %>
      <tr>
        <td><%= artiste.prenom %></td>
        <td><%= artiste.nom %></td>
        <td><%= link_to 'Show', artiste %></td>
        <td><%= link_to 'Edit', edit_artiste_path(artiste) %></td>
        <td><%= link_to 'Destroy', artiste, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artiste', new_artiste_path %>

app/views/artistes/new.html.erb
<h1>New Artiste</h1>

<%= render 'form', artiste: @artiste %>

<%= link_to 'Back', artistes_path %>

app/views/artistes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prenom:</strong>
  <%= @artiste.prenom %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @artiste.nom %>
</p>

<%= link_to 'Edit', edit_artiste_path(@artiste) %> |
<%= link_to 'Back', artistes_path %>

app/views/arts/_form.html.erb
<%= form_with(model: art, local: true) do |form| %>
  <% if art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_area :photo %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.number_field :date %>
  </div>

  <div class="field">
    <%= form.label :dimension %>
    <%= form.text_field :dimension %>
  </div>

  <div class="field">
    <%= form.label :titre %>
    <%= form.text_field :titre %>
  </div>

  <div class="field">
    <%= form.label :artiste_id %>
    <%= form.text_field :artiste_id %>
  </div>

  <div class="field">
    <%= form.label :description_id %>
    <%= form.text_field :description_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing Art</h1>

<%= render 'form', art: @art %>

<%= link_to 'Show', @art %> |
<%= link_to 'Back', arts_path %>

app/views/arts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Arts</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Date</th>
      <th>Dimension</th>
      <th>Titre</th>
      <th>Artiste</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arts.each do |art| %>
      <tr>
        <td><%= art.photo %></td>
        <td><%= art.date %></td>
        <td><%= art.dimension %></td>
        <td><%= art.titre %></td>
        <td><%= art.artiste %></td>
        <td><%= art.description %></td>
        <td><%= link_to 'Show', art %></td>
        <td><%= link_to 'Edit', edit_art_path(art) %></td>
        <td><%= link_to 'Destroy', art, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Art', new_art_path %>

app/views/arts/new.html.erb
<h1>New Art</h1>

<%= render 'form', art: @art %>

<%= link_to 'Back', arts_path %>

app/views/arts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%= @art.photo %>
</p>

<p>
  <strong>Date:</strong>
  <%= @art.date %>
</p>

<p>
  <strong>Dimension:</strong>
  <%= @art.dimension %>
</p>

<p>
  <strong>Titre:</strong>
  <%= @art.titre %>
</p>

<p>
  <strong>Artiste:</strong>
  <%= @art.artiste %>
</p>

<p>
  <strong>Description:</strong>
  <%= @art.description %>
</p>

<%= link_to 'Edit', edit_art_path(@art) %> |
<%= link_to 'Back', arts_path %>

app/views/descriptions/_form.html.erb
<%= form_with(model: description, local: true) do |form| %>
  <% if description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(description.errors.count, "error") %> prohibited this description from being saved:</h2>

      <ul>
      <% description.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :technique_utilise %>
    <%= form.text_field :technique_utilise %>
  </div>

  <div class="field">
    <%= form.label :l_histoire_de_l_oeuvre %>
    <%= form.text_field :l_histoire_de_l_oeuvre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/descriptions/edit.html.erb
<h1>Editing Description</h1>

<%= render 'form', description: @description %>

<%= link_to 'Show', @description %> |
<%= link_to 'Back', descriptions_path %>

app/views/descriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Descriptions</h1>

<table>
  <thead>
    <tr>
      <th>Technique utilise</th>
      <th>L histoire de l oeuvre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @descriptions.each do |description| %>
      <tr>
        <td><%= description.technique_utilise %></td>
        <td><%= description.l_histoire_de_l_oeuvre %></td>
        <td><%= link_to 'Show', description %></td>
        <td><%= link_to 'Edit', edit_description_path(description) %></td>
        <td><%= link_to 'Destroy', description, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Description', new_description_path %>

app/views/descriptions/new.html.erb
<h1>New Description</h1>

<%= render 'form', description: @description %>

<%= link_to 'Back', descriptions_path %>

app/views/descriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Technique utilise:</strong>
  <%= @description.technique_utilise %>
</p>

<p>
  <strong>L histoire de l oeuvre:</strong>
  <%= @description.l_histoire_de_l_oeuvre %>
</p>

<%= link_to 'Edit', edit_description_path(@description) %> |
<%= link_to 'Back', descriptions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>